### ISSUE TITLE
Milestone 4 deliverables

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/DSCI_522_group-307#61]
- [x] Create dependency diagram using `makefile2graph` 
- [x] Create `Dockerfile` (should live in root)
- [x] Update README
   - Add dependency diagram
   - Clearly document expected run time
   - Include instructions for running it with and without Docker
- [x] Create new release

**Comment by reikookamoto** [comment]
Dependency diagram resolved see #60
